package com.gathering.mock.fake.repository;

import com.gathering.book.model.domain.BookDomain;
import com.gathering.book.model.dto.BookSearchResponse;
import com.gathering.book.model.entity.Book;
import com.gathering.book.repository.BookRepository;
import com.gathering.common.base.exception.BaseException;
import com.gathering.common.base.response.BaseResponseStatus;
import org.springframework.data.domain.Pageable;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public class FakeBookRepository implements BookRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<BookDomain> data = new ArrayList<>();

    @Override
    public Book findBookByBookIdAndCategoryId(Long bookId, Long categoryId) {
        return null;
    }

    @Override
    public boolean existsByTitle(String title) {
        return false;
    }

    @Override
    public BookDomain save(BookDomain book) {
        return null;
    }

    @Override
    public Book save(Book book) {
        return null;
    }

    @Override
    public BookDomain findById(Long bookId) {
        return data.stream().filter(item -> Objects.equals(item.getId(), bookId))
                .findFirst()
                .orElseThrow(() -> new BaseException(BaseResponseStatus.NOT_EXISTED_BOOK));
    }

    @Override
    public List<BookSearchResponse> findPopularBooks(Pageable pageable) {
        return null;
    }

    @Override
    public List<Book> searchBooksBySearchWord(String title) {
        return null;
    }

    public BookDomain saveBook(BookDomain bookDomain) {
        if (Objects.isNull(bookDomain.getId())) {
            final BookDomain createBook = BookDomain.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .title(bookDomain.getTitle())
                    .image(bookDomain.getImage())
                    .publisher(bookDomain.getPublisher())
                    .author(bookDomain.getAuthor())
                    .publishDate(bookDomain.getPublishDate())
                    .selectedCount(bookDomain.getSelectedCount())
                    .star(bookDomain.getStar())
                    .introduce(bookDomain.getIntroduce())
                    .totalPage(bookDomain.getTotalPage())
                    .build();
            data.add(createBook);
            return createBook;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), bookDomain.getId()));
            data.add(bookDomain);
            return bookDomain;
        }
    }
}
