package com.gathering.mock.fake.repository;

import com.gathering.challenge.domain.ChallengeDomain;
import com.gathering.challenge.infrastructure.entity.Challenge;
import com.gathering.challenge.service.port.ChallengeRepository;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakeChallengeRepository implements ChallengeRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private List<ChallengeDomain> data = new ArrayList<>();

    @Override
    public ChallengeDomain save(ChallengeDomain challenge) {
        if(Objects.isNull(challenge.getId())) {
            final ChallengeDomain createChallenge = ChallengeDomain.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .challengeUsers(new ArrayList<>())
                    .challengeStatus(challenge.getChallengeStatus())
                    .completeRate(challenge.getCompleteRate())
                    .startDate(challenge.getStartDate())
                    .endDate(challenge.getEndDate())
                    .readingTimeGoal(challenge.getReadingTimeGoal())
                    .build();
            data.add(createChallenge);
            return createChallenge;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), challenge.getId()));
            data.add(challenge);
            return challenge;
        }
    }

    @Override
    public ChallengeDomain getByIdWithChallengeUsers(Long challengeId) {
        return data.stream().filter(item -> item.getId() == challengeId).findFirst().get();
    }

    @Override
    public Challenge findById(Long challengeId) {
        return null;
    }

    @Override
    public List<ChallengeDomain> getByIdsIn(List<Long> challengeIds) {
        return data.stream()
                .filter(challenge -> challengeIds.contains(challenge.getId()))
                .collect(Collectors.toList());
    }

    @Override
    public List<Long> findByStartDate(LocalDate today) {
        return data.stream()
                .filter(challenge -> challenge.getStartDate().equals(today))
                .mapToLong(ChallengeDomain::getId)
                .boxed()
                .collect(Collectors.toList());
    }

    @Override
    public ChallengeDomain findGatheringAndChallengeById(Long challengeId) {
        return data.stream()
                .filter(item -> item.getId() == challengeId)
                .findFirst()
                .get();
    }
}
